// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/redis/go-redis/v9"
	"github.com/th1enq/server_management_system/internal/config"
	"github.com/th1enq/server_management_system/internal/database"
	"github.com/th1enq/server_management_system/internal/handler"
	"github.com/th1enq/server_management_system/internal/repositories"
	"github.com/th1enq/server_management_system/internal/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(config2 *config.Config) (*App, error) {
	db, err := provideDB(config2)
	if err != nil {
		return nil, err
	}
	client, err := provideRedis(config2)
	if err != nil {
		return nil, err
	}
	serverRepository := repositories.NewServerRepository(db)
	serverService := services.NewServerService(serverRepository, client)
	serverHandler := handler.NewServerHandler(serverService)
	app := &App{
		Config:        config2,
		DB:            db,
		Redis:         client,
		ServerHandler: serverHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config        *config.Config
	DB            *gorm.DB
	Redis         *redis.Client
	ServerHandler *handler.ServerHandler
}

func provideDB(config2 *config.Config) (*gorm.DB, error) {
	err := database.LoadDB(config2)
	if err != nil {
		return nil, err
	}
	return database.DB, nil
}

func provideRedis(config2 *config.Config) (*redis.Client, error) {
	err := database.LoadRedis(config2)
	if err != nil {
		return nil, err
	}
	return database.RedisClient, nil
}
