// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/google/wire"
	"github.com/th1enq/server_management_system/internal/api"
	"github.com/th1enq/server_management_system/internal/api/http"
	"github.com/th1enq/server_management_system/internal/api/jobs"
	"github.com/th1enq/server_management_system/internal/app"
	"github.com/th1enq/server_management_system/internal/configs"
	"github.com/th1enq/server_management_system/internal/dataaccess"
	"github.com/th1enq/server_management_system/internal/dataaccess/cache"
	"github.com/th1enq/server_management_system/internal/dataaccess/database"
	"github.com/th1enq/server_management_system/internal/dataaccess/elasticsearch"
	"github.com/th1enq/server_management_system/internal/handler"
	"github.com/th1enq/server_management_system/internal/middleware"
	"github.com/th1enq/server_management_system/internal/repositories"
	"github.com/th1enq/server_management_system/internal/services"
	"github.com/th1enq/server_management_system/internal/utils"
)

// Injectors from wire.go:

func InitializeStandardServer(configFilePath configs.ConfigFilePath) (*app.StandaloneServer, func(), error) {
	config, err := configs.NewConfig(configFilePath)
	if err != nil {
		return nil, nil, err
	}
	server := config.Server
	log := config.Log
	logger, cleanup, err := utils.LoadLogger(log)
	if err != nil {
		return nil, nil, err
	}
	configsDatabase := config.Database
	db, cleanup2, err := database.LoadDB(configsDatabase, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pgxPoolInterface, cleanup3, err := database.LoadPgPool(configsDatabase, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverRepository := repositories.NewServerRepository(db, pgxPoolInterface)
	configsCache := config.Cache
	client, cleanup4, err := cache.LoadCache(configsCache, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serverService := services.NewServerService(serverRepository, client, logger)
	serverHandler := handler.NewServerHandler(serverService, logger)
	email := config.Email
	elasticSearch := config.Elasticsearch
	elasticsearchClient, cleanup5, err := elasticsearch.LoadElasticSearch(elasticSearch, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	reportService := services.NewReportService(email, elasticsearchClient, serverService, logger)
	reportHandler := handler.NewReportHandler(reportService, logger)
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository, logger)
	jwt := config.JWT
	tokenService := services.NewTokenService(jwt, logger, client)
	authService := services.NewAuthService(userService, tokenService, logger)
	authHandler := handler.NewAuthHandler(authService, logger)
	userHandler := handler.NewUserHandler(userService, logger)
	authMiddleware := middleware.NewAuthMiddleware(authService, logger)
	httpHandler := http.NewHandler(serverHandler, reportHandler, authHandler, userHandler, authMiddleware)
	httpServer := http.NewServer(server, logger, httpHandler)
	cron := config.Cron
	sendDailyReport := jobs.NewSendDailyReport(reportService)
	intervalCheckStatus := jobs.NewIntervalCheckStatus(serverService)
	standaloneServer := app.NewStandaloneServer(httpServer, logger, cron, sendDailyReport, intervalCheckStatus)
	return standaloneServer, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(app.WireSet, configs.WireSet, handler.WireSet, dataaccess.WireSet, api.WireSet, repositories.WireSet, services.WireSet, middleware.WireSet, utils.WireSet)
