server:
  name: VCS-SMS
  env: development
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: vcs_sms
  max_idle_conns: 10
  max_open_conns: 100

tsdb:
  host: localhost
  port: 8086
  db: metrics
  user: admin
  password: admin123

broker:
  addresses:
    - localhost:9092

cache:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

elasticsearch:
  url: http://localhost:9200

jwt:
  secret: c2xoqMG2nvNhRJG9GnTG2gqA+uaNObrxARU2f6Ya7IQ=
  expiration: 24h

log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30

cron:
  update_status:
    name: "update_status"
    schedule: "@every 15s"  
  daily_report:
    name: "daily_report"
    schedule: "0 0 8 * * *"

dispatcher:
  process_interval: 20s
  lock_checker_interval: 600m
  cleanup_worker_interval: 60s
  max_lock_time_duration: 5m
  messages_retention_duration: 1m
  machine_id: "machine-1"

email:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: thienchy3305@gmail.com
  password: rtac iyoq zaad rkui
  from: thienchy3305@gmail.com
  admin_email: miyaki08x@gmail.com
