server:
  name: VCS-SMS
  env: development
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: vcs_sms
  max_idle_conns: 10
  max_open_conns: 100

tsdb:
  host: localhost
  port: 8086
  db: metrics
  user: admin
  password: admin123

mq:
  addresses:
    - localhost:9092
  client_id: "vcs_sms"
  consumer_groups:
    - group_id: "vcs_sms-metrics"
      topics: 
        - "monitoring_event"
    - group_id: "vcs_sms-status"
      topics:
        - "monitoring_event"

cache:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

elasticsearch:
  url: http://localhost:9200

jwt:
  secret: c2xoqMG2nvNhRJG9GnTG2gqA+uaNObrxARU2f6Ya7IQ=
  expiration: 24h

log:
  level: info
  file_path: ./logs/app.log
  max_size: 100
  max_backups: 10
  max_age: 30

cron:
  update_status:
    name: "update_status"
    schedule: "@every 20s"  
  daily_report:
    name: "daily_report"
    schedule: "0 0 8 * * *"

email:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  username: thienchy3305@gmail.com
  password: rtac iyoq zaad rkui
  from: thienchy3305@gmail.com
  admin_email: miyaki08x@gmail.com
